# Site settings
title: Nic H
email: <unspecified>@email.com
description: >
    This is my personal website.  It contains some information about my work, my hobbies, and whatever comes to mind.
baseurl: "/nic_h"
url: "http://scyptnex.github.io"
fixedNav: 'true' # true or false
theme: green # purple green, blue, orange, purple, grey
githubUsername: scyptnex
#twitterUsername:
#dribbbleUsername:
#codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, .gitignore, theme.license]
sass:
  style: compressed
