# Site settings
title: Nic H
tagline: Obligatory Website
email: <unspecified>@email.com
description: >
    This is my personal website.  It contains some information about my work, my hobbies, and whatever comes to mind.
baseurl: ""
url: "http://scyptnex.github.io"
fixedNav: 'true' # true or false

# Build settings
permalink: pretty
markdown: kramdown
include: [_pages]
exclude: [_site, .gitignore]
